server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.security.jackson2: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'false'
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: 'false'

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
